"""create initial tables

Revision ID: 922bd88d6505
Revises:
Create Date: 2026-10-07 12:25:37.987062

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "922bd88d6505"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["categories.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("parent_id", "name"),
    )
    with op.batch_alter_table("categories", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_categories_parent_id"), ["parent_id"], unique=False
        )

    op.create_table(
        "tag_groups",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "recipes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("servings", sa.String(), nullable=True),
        sa.Column("active_time_minutes", sa.Integer(), nullable=True),
        sa.Column("total_time_minutes", sa.Integer(), nullable=True),
        sa.Column("source_notes", sa.Text(), nullable=True),
        sa.Column("category_id", sa.Integer(), nullable=True),
        sa.Column(
            "source_type",
            sa.Enum("link", "image", "text", name="sourcetype"),
            nullable=False,
        ),
        sa.Column("source_url", sa.String(), nullable=True),
        sa.Column(
            "status", sa.Enum("draft", "saved", name="recipestatus"), nullable=False
        ),
        sa.Column("suggested_tags", sa.JSON(), nullable=True),
        sa.Column("extraction_method", sa.String(), nullable=True),
        sa.Column("extraction_model", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("recipes", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_recipes_category_id"), ["category_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_recipes_source_url"), ["source_url"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_recipes_status"), ["status"], unique=False)

    op.create_table(
        "tags",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("tag_group_id", sa.Integer(), nullable=False),
        sa.Column(
            "is_pinned", sa.Boolean(), server_default=sa.text("0"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["tag_group_id"],
            ["tag_groups.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    with op.batch_alter_table("tags", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_tags_tag_group_id"), ["tag_group_id"], unique=False
        )

    op.create_table(
        "images",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("recipe_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("file_path", sa.String(), nullable=False),
        sa.Column("file_hash", sa.String(length=64), nullable=False),
        sa.Column("perceptual_hash", sa.String(length=16), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["recipe_id"], ["recipes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("images", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_images_file_hash"), ["file_hash"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_images_recipe_id"), ["recipe_id"], unique=False
        )

    op.create_table(
        "ingredients",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("recipe_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("group_label", sa.String(), nullable=True),
        sa.Column("quantity", sa.Double(), nullable=True),
        sa.Column("quantity_max", sa.Double(), nullable=True),
        sa.Column("unit", sa.String(), nullable=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("base_name", sa.String(), nullable=False),
        sa.Column("note", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["recipe_id"], ["recipes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("ingredients", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_ingredients_base_name"), ["base_name"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_ingredients_recipe_id"), ["recipe_id"], unique=False
        )

    op.create_table(
        "recipe_tags",
        sa.Column("recipe_id", sa.Integer(), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["recipe_id"], ["recipes.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tag_id"], ["tags.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("recipe_id", "tag_id"),
    )
    with op.batch_alter_table("recipe_tags", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_recipe_tags_tag_id"), ["tag_id"], unique=False
        )

    op.create_table(
        "steps",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("recipe_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("group_label", sa.String(), nullable=True),
        sa.Column("text", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(["recipe_id"], ["recipes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("steps", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_steps_recipe_id"), ["recipe_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("steps", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_steps_recipe_id"))

    op.drop_table("steps")
    with op.batch_alter_table("recipe_tags", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_recipe_tags_tag_id"))

    op.drop_table("recipe_tags")
    with op.batch_alter_table("ingredients", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_ingredients_recipe_id"))
        batch_op.drop_index(batch_op.f("ix_ingredients_base_name"))

    op.drop_table("ingredients")
    with op.batch_alter_table("images", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_images_recipe_id"))
        batch_op.drop_index(batch_op.f("ix_images_file_hash"))

    op.drop_table("images")
    with op.batch_alter_table("tags", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_tags_tag_group_id"))

    op.drop_table("tags")
    with op.batch_alter_table("recipes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_recipes_status"))
        batch_op.drop_index(batch_op.f("ix_recipes_source_url"))
        batch_op.drop_index(batch_op.f("ix_recipes_category_id"))

    op.drop_table("recipes")
    op.drop_table("tag_groups")
    with op.batch_alter_table("categories", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_categories_parent_id"))

    op.drop_table("categories")
    # ### end Alembic commands ###
